### ISSUE TITLE
Unable to sync with device; possible link problem or link software version mismatch such as hydro rosserial_python with groovy Arduino

### ISSUE THREAD

**Issue by zakizadeh** [grassjelly/ros_braccio_moveit#1]
hi . i uplod [this code](https://github.com/grassjelly/ros_braccio_moveit/blob/master/teensy/src/firmware.ino) on arduino mega 2560 . and run [this launch file](https://github.com/grassjelly/ros_braccio_moveit/blob/master/launch/demo.launch) . i have this error :

Unable to sync with device; possible link problem or link software version mismatch such as hydro rosserial_python with groovy Arduino
baud rate is 115200 . but my servo motors not working .

**Comment by grassjelly** [comment]
I ran this on a Teensy 3.1 as I was having similar issues with an Arduino Uno/Mega. Would be glad to hear your results. https://github.com/grassjelly/ros_braccio_moveit/blob/master/launch/demo.launch#L50 take note that you have to change the serial port (ie. /dev/ttyACM0).

**Comment by zakizadeh** [comment]
yes . i changed serial port . but i alsoo change baud rate to 200000 and now servo motor are vorking .
