### ISSUE TITLE
how can i store entire trajectory in Arduino and then execute it once ??

### ISSUE THREAD

**Issue by zakizadeh** [grassjelly/ros_braccio_moveit#2]
hi . i run  [demo](https://github.com/grassjelly/ros_braccio_moveit/blob/master/launch/demo.launch) and upload [this file](https://github.com/grassjelly/ros_braccio_moveit/blob/master/teensy/src/firmware.ino) in arduino . but i need store entire trajectory in Arduino and then execute it once I received it all. my robot stopping between commands.

**Comment by grassjelly** [comment]
Hi, 

The Arduino is subscribed to join_states (to be changed soon) which translates the received positions into servo movements. The arm should execute and move towards the pose you set through the interactive marker in rviz.

**Comment by zakizadeh** [comment]
i added delay in program and now it work . my robot and rviz are sync .
